[package]
name = "rw-format-html"
description = "HTML import/export for Rust Writer"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
html5ever = { workspace = true }
markup5ever = { workspace = true }
rw-document = { workspace = true }
rw-styles = { workspace = true }
