[package]
name = "file_ops"
version.workspace = true
edition.workspace = true

[dependencies]
shared = { workspace = true }
utils = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
tempfile = "3.15"
tokio = { workspace = true, features = ["test-util", "macros"] }
