[package]
name = "conversion"
version.workspace = true
edition.workspace = true

[dependencies]
shared = { workspace = true }
thiserror = { workspace = true }
comrak = { workspace = true }
docx-rs = { workspace = true }
tempfile = "3.15"

[dev-dependencies]
tokio = { workspace = true, features = ["test-util", "macros"] }
tempfile = "3.15"
