[package]
name = "oxysf-org"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "The 'org' command topic for oxy-sf (login, logout, list, display)."

[dependencies]
oxysf-core = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
